version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: paragon_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: paragon
      POSTGRES_PASSWORD: couture_secret
      POSTGRES_DB: paragon_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
